### ISSUE TITLE
Starting from Xcode 14, resource bundles are signed by default, which requires setting the development team for each resource bundle target.

### ISSUE THREAD

**Issue by marcjimenez** [andrew-levy/react-native-safari-extension#11]
Great job on the config plugin! Running into an issue when attempting to build via expo. After I run 

```
yarn eas build --profile preview --platform ios
```

I get the following error 

```
🍎 iOS build failed:
Starting from Xcode 14, resource bundles are signed by default, which requires setting the development team for each resource bundle target.
To resolve this issue, downgrade to an older Xcode version using the "image" field in eas.json, or upgrade to SDK 46 or higher.
Learn more: https://docs.expo.dev/build-reference/infrastructure/#ios-build-server-configurations
```

I have gone ahead and done what the resolution suggests but still can not seem to get this to work. Is this something that you guys have run into, if so any suggestions?

**Comment by andrew-levy** [comment]
Hey thanks for pointing this out! I haven't tried using this with xcode 14 or expo 46, so it's very possible this is an issue. Did you try opening xcode and setting the development team manually? I can look into this more this week to see if there's a way to automatically add the development team without having to open xcode

**Comment by andrew-levy** [comment]
@marcjimenez I just ran `eas build -p ios --profile preview` on one of my example projects, with the `image` field set to `latest` (uses xcode 14)

```
Build failed: Starting from Xcode 14, resource bundles are signed by default, which requires setting the development team for each resource bundle target.
To resolve this issue, downgrade to an older Xcode version using the "image" field in eas.json, or turn off signing resource bundles in your Podfile: https://expo.fyi/r/disable-bundle-resource-signing
```
Replacing the `post_install` command in `Poddfile` with the following, found here https://expo.fyi/r/disable-bundle-resource-signing,  seems to have fixed the issue for me, kinda a work around tho. 

```ruby
post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
```

Let me know if that works for you!

**Comment by andrew-levy** [comment]
Great news! I'll go ahead and add that to the docs
