### ISSUE TITLE
support messaging between extension and native app?

### ISSUE THREAD

**Issue by bengoism** [andrew-levy/react-native-safari-extension#15]
Are there any plans to add support for sending messages from extension to the native app? as described in the docs here: https://developer.apple.com/documentation/safariservices/safari_web_extensions/messaging_between_the_app_and_javascript_in_a_safari_web_extension

**Comment by andrew-levy** [comment]
Hey @bengoism. As of right now there isn't a way to receive a message from the extension, but this would be great to add. Right now, this library serves as a way to quickly set up an extension, and inject react native web code into the extension sheet, but i haven't gotten around to adding any native functionality like sending events or checking to see if the extension is enabled/disabled. If this is something you're interested in adding, please feel free to contribute, but if not I will eventually try to add this. 

And just a heads up, this library is pretty experimental at this point. I ran into some issues the other day trying to use it and need to push out some changes to fix the issues.

**Comment by nickcruz** [comment]
Hi! This should fix the linking:
- #17

I was getting this native error and the log seemed to suggest it:
```
__extensionPrincipalClass != nil - /Library/Caches/com.apple.xbs/Sources/ExtensionFoundation_Sim/ExtensionFoundation/Source/NSExtension/NSExtensionSupport/EXConcreteExtensionContextVendor.m:109: Unable to find NSExtensionPrincipalClass (SafariWebExtensionHandler) in extension bundle! Please verify that the extension links the required frameworks and that the value for NSExtensionPrincipalClass is prefixed with '$(PRODUCT_MODULE_NAME).' if the class is implemented in Swift.
```

The [sample code](https://developer.apple.com/documentation/safariservices/safari_web_extensions/developing_a_safari_web_extension) also has this in its Info.Plist.

![image](https://github.com/andrew-levy/react-native-safari-extension/assets/8432766/c6d4bc03-e853-4c9f-8fe1-2f17b0aa454b)
