### ISSUE TITLE
Extension.entitlements could not be opened

### ISSUE THREAD

**Issue by robertherber** [andrew-levy/react-native-safari-extension#5]
I'm running into this error when building a Expo Dev Client locally:
```❌  error: The file "/var/folders/px/xg99v_l53hbc4yy9_58c23q00000gn/T/eas-build-local-nodejs/7a5ecf27-d085-4f25-8c3c-427341cfcdb1/build/ios/DEVExtension/DEVExtension.entitlements" could not be opened. Verify the value of the CODE_SIGN_ENTITLEMENTS build setting for target "DEVExtension" is correct and that the file exists on disk. (in target 'DEVExtension' from project 'DEV')```

I tried commenting out the CODE_SIGN_ENTITLEMENTS in `addXCConfigurationList`:
```// CODE_SIGN_ENTITLEMENTS: `${extensionFolder}/${extensionFolder}.entitlements`,```
but then I get `Signing for "DEVExtension" requires a development team` - which I guess makes sense.

Any ideas on how to proceed? How do I generate the entitlements? Does it require an AppStore build maybe?

**Comment by andrew-levy** [comment]
can you provide steps to recreate this issue?

**Comment by robertherber** [comment]
I got the signing error when commenting it out:
`Signing for "DEVExtension" requires a development team`

**Comment by robertherber** [comment]
@andrew-levy Here are repros of both cases:
[Original repro](https://github.com/robertherber/react-native-safari-extension-repro)
[Repro when commenting out](https://github.com/robertherber/react-native-safari-extension-repro/tree/commented-out)

In both cases just `yarn install` and `yarn build-local` to reproduce each respective error. Hope it helps - and let me know if I can help in any other way! 🙂

**Comment by robertherber** [comment]
@andrew-levy I get the same error as when commenting it out, i.e.:
`Signing for "***Extension" requires a development team. Select a development team in the Signing & Capabilities editor.`

I'm guessing it's `eas-cli` that doesn't set the development team for extensions for some reason? Curious as how it can work differently in such a barebones repro on our respective machines.

**Comment by robertherber** [comment]
@andrew-levy Thanks for showing your process. With `expo run:ios` I get another error:
`reproioswebextensionExtension/Resources/popup.js: No such file or directory`

Could you try running `yarn build-local` on the repro to see if you get the same as me? I guess `eas-cli build` and `expo run:ios` might behave a bit differently.

**Comment by andrew-levy** [comment]
Yes, you're getting that error because the project assumes a certain file structure. This is another bug I need to address (and will soon)

I tried running `yarn build-local` which fails because I don't have an apple developer account. I have only tested this repo with local builds, not in the cloud unfortunately. Sorry for the bugs, as its still in very early development.

**Comment by andrew-levy** [comment]
Thanks! yes I based this plugin off of the app clip plugin. I'll have to dig into it more to see what the difference is (i may have missed something)
